modLoader="kotlinforforge"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/DeflatedPickle/SquidMilk/issues"
[[mods]]
modId="squidmilk"
version="${file.jarVersion}"
displayName="SquidMilk"
displayURL="https://github.com/DeflatedPickle/SquidMilk"
logoFile="logo.png"
credits="Mojang, Minecraft, Forge, FML"
authors="DeflatedPickle"
description='''
'''